def get_hp_config():
    """
    Contains the hyperparameter configurations for model training.
    This configuration is "operational" so modifying these settings will impact the model's behavior during the training.

    Returns:
    - hyperparameters (dict): A dictionary containing hyperparameters for training the model, which determine the model's behavior during the training phase.
    """
    
    hyperparameters = {
        "steps": [*range(1, 36 + 1, 1)],
        "num_samples": 1,
        "mc_dropout": True,
        "random_state": 67,
        "batch_size": 2048,
        "decoder_output_dim": 128,
        "delta": 0.7963233371393438,
        "dropout": 0.05,
        "early_stopping_min_delta": 0.0001,
        "early_stopping_patience": 20,
        "false_negative_weight": 3.0232921185801342,
        "false_positive_weight": 0.8673793804297499,
        "feature_scaler": None,
        "feature_scaler_map": {
            "MinMaxScaler": [
                "lr_wdi_sl_tlf_totl_fe_zs",
                "lr_wdi_se_enr_prim_fm_zs",
                "lr_wdi_sp_urb_totl_in_zs",
                "lr_wdi_sh_sta_maln_zs",
                "lr_wdi_sh_sta_stnt_zs",
                "lr_wdi_dt_oda_odat_pc_zs",
                "lr_wdi_ms_mil_xpnd_gd_zs",
                "lr_vdem_v2x_horacc",
                "lr_vdem_v2xnp_client",
                "lr_vdem_v2x_veracc",
                "lr_vdem_v2x_divparctrl",
                "lr_vdem_v2xpe_exlpol",
                "lr_vdem_v2x_diagacc",
                "lr_vdem_v2xpe_exlgeo",
                "lr_vdem_v2xpe_exlgender",
                "lr_vdem_v2xpe_exlsocgr",
                "lr_vdem_v2x_ex_party",
                "lr_vdem_v2x_genpp",
                "lr_vdem_v2xeg_eqdr",
                "lr_vdem_v2xcl_prpty",
                "lr_vdem_v2xeg_eqprotec",
                "lr_vdem_v2x_ex_military",
                "lr_vdem_v2xcl_dmove",
                "lr_vdem_v2x_clphy",
                "lr_vdem_v2x_hosabort",
                "lr_vdem_v2xnp_regcorr",
                "lr_topic_ste_theta0",
                "lr_topic_ste_theta1",
                "lr_topic_ste_theta2",
                "lr_topic_ste_theta3",
                "lr_topic_ste_theta4",
                "lr_topic_ste_theta5",
                "lr_topic_ste_theta6",
                "lr_topic_ste_theta7",
                "lr_topic_ste_theta8",
                "lr_topic_ste_theta9",
                "lr_topic_ste_theta10",
                "lr_topic_ste_theta11",
                "lr_topic_ste_theta12",
                "lr_topic_ste_theta13",
                "lr_topic_ste_theta14",
                "lr_topic_ste_theta0_stock_t1_splag",
                "lr_topic_ste_theta1_stock_t1_splag",
                "lr_topic_ste_theta2_stock_t1_splag",
                "lr_topic_ste_theta3_stock_t1_splag",
                "lr_topic_ste_theta4_stock_t1_splag",
                "lr_topic_ste_theta5_stock_t1_splag",
                "lr_topic_ste_theta6_stock_t1_splag",
                "lr_topic_ste_theta7_stock_t1_splag",
                "lr_topic_ste_theta8_stock_t1_splag",
                "lr_topic_ste_theta9_stock_t1_splag",
                "lr_topic_ste_theta10_stock_t1_splag",
                "lr_topic_ste_theta11_stock_t1_splag",
                "lr_topic_ste_theta12_stock_t1_splag",
                "lr_topic_ste_theta13_stock_t1_splag",
                "lr_topic_ste_theta14_stock_t1_splag",
                "lr_wdi_sp_pop_grow",
            ],
            "AsinhTransform->MinMaxScaler": [
                "lr_ged_sb",
                "lr_ged_ns",
                "lr_ged_os",
                "lr_acled_sb",
                "lr_acled_sb_count",
                "lr_acled_os",
                "lr_ged_sb_tsum_24",
                "lr_splag_1_ged_sb",
                "lr_splag_1_ged_os",
                "lr_splag_1_ged_ns",
                "lr_wdi_ny_gdp_mktp_kd",
                "lr_wdi_nv_agr_totl_kn",
                "lr_wdi_sm_pop_netm",
                "lr_wdi_sm_pop_refg_or",
                "lr_wdi_sp_dyn_imrt_fe_in",
                "lr_topic_tokens_t1",
                "lr_topic_tokens_t1_splag",
            ],
        },
        "force_reset": True,
        "gradient_clip_val": 1.1726061018759937,
        "hidden_size": 32,
        "input_chunk_length": 36,
        "loss_function": "WeightedPenaltyHuberLoss",
        "lr": 0.00007763945427535866,
        "lr_scheduler_factor": 0.5,
        "lr_scheduler_min_lr": 1e-6,
        "lr_scheduler_patience": 8,
        "n_epochs": 150,
        "non_zero_weight": 40.45796070375936,
        "num_decoder_layers": 2,
        "num_encoder_layers": 3,
        "output_chunk_shift": 0,
        "output_chunk_length": 36,
        "target_scaler": "AsinhTransform->MinMaxScaler",
        "temporal_decoder_hidden": 256,
        "temporal_hidden_size_future": 128,
        "temporal_hidden_size_past": 128,
        "temporal_width_future": 36,
        "temporal_width_past": 36,
        "use_layer_norm": False,
        "use_reversible_instance_norm": True,
        "use_static_covariates": False,
        "weight_decay": 0,
        "zero_threshold": 0.21142621340530116,
    }

    return hyperparameters