"""
Falsification test stubs for claim: "The 6 synthetic models and 3 synthetic ensembles
produce correct, internally consistent outputs matching documented configurations."
Generated by /falsify audit on 2026-05-26

These tests are in TDD RED state -- they FAIL against the current code.
Fix the code to make them pass, then re-run /falsify to verify and check for regressions.
"""

import pytest
from tests.conftest import REPO_ROOT


@pytest.mark.beige
def test_falsify_01_synthetic_chant_readme_documents_crps_inflation():
    """
    Probe 1 (Category E): CRPS inflation anomaly in synthetic_chant.

    Finding: synthetic_chant reports CRPS=1.044 while its constituents have
    CRPS of 0.000, 0.002, and 0.043. The 24x degradation is caused by the
    ensemble evaluating all predictions against lucid_dream's actuals
    (vertical_stripe pattern), while vivid_dream and waking_dream were
    trained on horizontal_stripe and diagonal_gradient respectively.
    This is expected framework behavior (models[0] actuals selection)
    but the README does not document it.

    Severity: soft

    Expected: The README should explain that constituent models use
    different synthetic patterns, that ensemble CRPS reflects cross-pattern
    disagreement (not prediction quality), and which model's actuals are
    used for evaluation.
    """
    readme = (REPO_ROOT / "ensembles" / "synthetic_chant" / "README.md").read_text()
    readme_lower = readme.lower()
    has_pattern_explanation = (
        "vertical_stripe" in readme
        or "different pattern" in readme_lower
        or "different synthetic pattern" in readme_lower
        or "heterogeneous" in readme_lower
    )
    has_actuals_explanation = (
        "models[0]" in readme
        or "ground truth" in readme_lower
        or "actuals" in readme_lower
        or "evaluated against" in readme_lower
    )
    assert has_pattern_explanation and has_actuals_explanation, (
        "synthetic_chant README does not document that (1) constituent models use "
        "different synthetic patterns and (2) ensemble CRPS is evaluated against "
        "the first model's actuals only, making the metric reflect cross-pattern "
        "disagreement rather than prediction quality"
    )
