"""Falsification stubs — deployment_status convention (rusty_bucket / FAO-only).

Generated by /falsify on the claim: "deployment_status is a consumer/channel-
agnostic lifecycle axis; rusty_bucket can be `shadow` now → `deployed` when live,
and FAO-only holds by construction."

VERDICT: CONTESTED — 1 soft falsification (P3). The claim's mechanism survives
(nothing serves/schedules by status; monthly_run.sh membership controls the
channel; white_mustang is the precedent), BUT the guard that should keep a
`deployed` ensemble coherent with its constituents is DEAD, and the proposed
solution never addressed constituent status.

These tests are EXPECTED TO FAIL / are placeholders until the gap is closed.
"""

import importlib.util
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
ENSEMBLES_DIR = REPO_ROOT / "ensembles"


def _load(path):
    spec = importlib.util.spec_from_file_location("m", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _status(config_dir):
    f = config_dir / "config_deployment.py"
    return _load(f).get_deployment_config().get("deployment_status") if f.exists() else None


# ── P3 (soft): "deployed ensemble ⇒ deployed constituents" is unenforced ──────
# pipeline-core validate_ensemble_model_deployment_status() only rejects the
# combination via `single_model_dp_status == "production"`, but "production" is
# NOT in SUPPORTED_DEPLOYMENT_STATUSES ({shadow, deployed, baseline, deprecated}),
# so the rule can never fire. A `deployed` ensemble of `shadow` constituents
# passes validation silently. The proposed convention ("flip rusty_bucket to
# deployed when live") never said the constituents must flip too.

@pytest.mark.xfail(
    reason="Known live violation: white_mustang (deployed) has shadow constituents "
    "(lavender_haze, blank_space) — the pipeline-core coherence guard is dead "
    "(C-95 review finding; pending the ADR-017 verdict). Flips to a hard gate "
    "when the rule is decided + the violation resolved.",
    strict=False,
)
def test_deployed_ensemble_has_no_shadow_constituents():
    """A `deployed` ensemble must not be built from `shadow` constituents.

    Encodes the invariant the broken pipeline-core guard fails to enforce. Will
    expose any current/future deployed-ensemble-of-shadow-models inconsistency
    (and is the missing piece of the rusty_bucket→deployed plan).
    """
    violations = []
    for ens in sorted(p for p in ENSEMBLES_DIR.iterdir() if (p / "configs").is_dir()):
        if _status(ens / "configs") != "deployed":
            continue
        modelset_f = ens / "configs" / "config_modelset.py"
        if not modelset_f.exists():
            continue
        models = _load(modelset_f).get_modelset_config().get("models", [])
        for m in models:
            if _status(REPO_ROOT / "models" / m / "configs") == "shadow":
                violations.append(f"{ens.name} (deployed) ← {m} (shadow)")
    assert not violations, (
        "deployed ensembles built from shadow constituents (unguarded by "
        f"pipeline-core check.py): {violations}"
    )


@pytest.mark.xfail(reason="pipeline-core check.py compares to unsupported literal 'production'", strict=False)
def test_ensemble_guard_uses_supported_vocabulary():
    """The ensemble deployment-status guard must branch on a SUPPORTED status.

    pipeline-core/.../validation/ensemble/check.py keys on `== "production"`,
    a value the sniffer forbids (SUPPORTED = {shadow, deployed, baseline,
    deprecated}). The rule is therefore dead. Fails until the literal is fixed
    to `"deployed"`. Skips if pipeline-core is not checked out next to this repo.
    """
    check = REPO_ROOT.parent / "views-pipeline-core" / "views_pipeline_core" / "modules" / "validation" / "ensemble" / "check.py"
    if not check.exists():
        pytest.skip("views-pipeline-core not located for source check")
    src = check.read_text()
    assert not re.search(r'==\s*["\']production["\']', src), (
        "check.py branches on unsupported literal 'production' — dead rule; "
        "should compare to 'deployed'"
    )
