"""Falsification tests from audit of catalog enhancements (#86-#91).

Generated by /falsify audit on 2026-06-05.
Fixed: characterization docstring updated, _FIXTURE_ENTRIES extended.
"""
import pytest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

pytestmark = pytest.mark.green


class TestCharacterizationCopyFidelity:
    """F1: test_tooling_scripts.py::_format_name_cell must not claim 'Exact copy'."""

    def test_characterization_name_cell_docstring_honest(self):
        """The characterization approximates create_link() — docstring must say so."""
        import inspect
        import sys
        sys.path.insert(0, str(REPO_ROOT / "tests"))
        from test_tooling_scripts import _format_name_cell
        doc = inspect.getdoc(_format_name_cell) or ""
        assert "Exact copy" not in doc, (
            "_format_name_cell docstring still claims 'Exact copy' "
            "but it approximates create_link() with an f-string"
        )


class TestSyntheticEntriesInCatalog:
    """F2: Synthetic test models appear in production README catalog."""

    def test_fixture_entries_excludes_synthetic_models(self):
        """
        Probe #4 (Category E): _FIXTURE_ENTRIES consistency.

        Finding: _FIXTURE_ENTRIES = {"fake_model", "test_model",
        "test_ensemble"} does not include synthetic test models
        (diagonal_dream, horizontal_dream, lucid_dream, vertical_dream,
        vivid_dream, waking_dream) or synthetic ensembles
        (synthetic_chant, synthetic_choir, synthetic_chorus).
        These 13 entries appear in the production README catalog.
        Severity: Soft falsification.

        Expected: Test/scaffold entries should not appear in production
        documentation, or _FIXTURE_ENTRIES should be extended.
        """
        import sys
        sys.path.insert(0, str(REPO_ROOT))
        from create_catalogs import _FIXTURE_ENTRIES

        synthetic_names = {
            "diagonal_dream", "horizontal_dream", "lucid_dream",
            "vertical_dream", "vivid_dream", "waking_dream",
            "synthetic_chant", "synthetic_choir", "synthetic_chorus",
        }
        missing = synthetic_names - _FIXTURE_ENTRIES
        assert not missing, (
            f"Synthetic test entries not in _FIXTURE_ENTRIES: {missing}. "
            f"These appear in the production README catalog."
        )
