def get_hp_config():
    """
    Contains the hyperparameter configurations for preprocessor training.
    This configuration is "operational" so modifying these settings will impact the preprocessor's behavior during the training.

    Returns:
    - hyperparameters (dict): A dictionary containing hyperparameters for training the preprocessor, which determine the preprocessor's behavior during the training phase.
    """

    hyperparameters = {
        "topics": ["Education & Jobs", "Crime & Law"],
        "priority_topic": "Education & Jobs",
        "n_sublists": 4,
        "shared_ratio": 0.25,
        "majority": 3,
        "random_seed": 42,
        "llm": "snowood1/ConfliBERT-scr-uncased",
        "max_samples": 2000,
        "batch_size": 8,  # 100
        "dropout_prob": 0.1,
        "monte_carlo_runs": 100,
        "learning_rate": 1e-5,
        "num_train_epochs": 10,
        "evaluation_strategy": "steps",
        "eval_steps": 10,
        "save_strategy": "steps",
        "save_steps": 10,
        "save_total_limit": 1,
        "load_best_model_at_end": True,
        "early_stopping_patience": 3,  # Stop training if no improvement for 3 epochs
        "early_stopping_threshold": 0.01,  # Improvement must > 1% to be considered
        "metric_for_best_model": "eval_loss",
        "metrics": ["accuracy", "f1"],
        "doccano_url": "http://localhost:8000",  # "doccano_url": "http://localhost:5900",
        "doccano_user": "admin",
        "doccano_password": "password",
        "project_name": [
            "Edattack_Annotator1_Gudrun",
            "Edattack_Annotator2_Roos",
            "Edattack_Annotator_3_Kristine",
            "Edattack_Annotator4_Sonja",
            "Consensus_Edattack",
        ],
        "max_iterations": 10,
        "disagreement_strategy": 1,
        "query_size": 10,
        "min_batch_size": 3,
        "annotation_size": 20,
        "labels": {
            "Violence": 0,
            "Arrest & Detention": 1,
            "Recruitment & Abduction": 2,
            "Sexual Violence": 3,
            "Threats/Intimidation": 4,
            "Target: Student": 6,
            "Target: Personnel": 7,
            "Target: Infrastructure": 8,
            "Victim Gender: Female mentioned": "a",
            "Victim Gender: Male mentioned": "b",
            "Non-binary mentioned": "c",
            "Institution: Female-focused": "d",
            "Institution: Male-focused": "e",
            "Educational Level: Primary": "f",
            "Educational Level: Secondary": "g",
            "Educational Level: Higher": "h",
            "Incidental Flag": "i",
            "No attack on education": "k",
            "In Educational Role": "j",
        },
        "colours": {
            "Violence": "#8a9bee",
            "Arrest & Detention": "#8a9bee",
            "Recruitment & Abduction": "#8a9bee",
            "Sexual Violence": "#8a9bee",
            "Threats/Intimidation": "#8a9bee",
            "Target: Student": "#40864A",
            "Target: Personnel": "#40864A",
            "Target: Infrastructure": "#40864A",
            "Victim Gender: Female mentioned": "#868440",
            "Victim Gender: Male mentioned": "#868440",
            "Non-binary mentioned": "#868440",
            "Institution: Female-focused": "#868440",
            "Institution: Male-focused": "#868440",
            "Educational Level: Primary": "#C1C1B7",
            "Educational Level: Secondary": "#C1C1B7",
            "Educational Level: Higher": "#C1C1B7",
            "Incidental Flag": "#D594C8",
            "No attack on education": "#611C1E",
            "In Educational Role": "#D5963C",
        },
        # --- Preselection settings ---
        "preselection": {
            "engine": "spacy",  # "spacy" or "hf"
            "spacy_model": "en_core_web_sm",
            "spacy_disable": ["ner"],
            "edu_places": [
                "school",
                "primary school",
                "secondary school",
                "high school",
                "college",
                "university",
                "campus",
                "classroom",
                "lecture hall",
                "kindergarten",
                "nursery",
                "madrasah",
                "madrasa",
                "madrassa",
                "academy",
                "institute",
                "polytechnic",
                "boarding school",
                "dorm",
                "dormitory",
                "school bus",
                "school van",
                "playground",
                "schoolyard",
                "faculty",
                "faculty of education",
                "department",
                "department of education",
                "tutoring center",
                "tuition center",
                "coaching center",
                "coaching class",
                "tuition centre",
                "coaching centre",
            ],
            "edu_persons": [
                "student",
                "pupil",
                "teacher",
                "professor",
                "lecturer",
                "headteacher",
                "headmaster",
                "headmistress",
            ],
            "edu_head_hints": [
                "school",
                "university",
                "college",
                "campus",
                "academy",
                "institute",
                "polytechnic",
                "dormitory",
                "dorm",
                "faculty",
                "department",
            ],
            "attack_terms": [
                "attack",
                "assault",
                "storm",
                "raid",
                "ambush",
                "clash",
                "bomb",
                "car bomb",
                "improvised explosive device",
                "ied",
                "airstrike",
                "air strike",
                "shell",
                "shelling",
                "mortar",
                "rocket",
                "grenade",
                "shoot",
                "open fire",
                "gun down",
                "fire shots",
                "fired shots",
                "open fires",
                "kill",
                "injure",
                "wound",
                "stab",
                "burn",
                "torch",
                "arson",
                "firebomb",
                "set ablaze",
                "set alight",
                "set on fire",
                "explode",
                "detonate",
                "blast",
                "explosion",
                "shrapnel",
                "debris",
                "vandalize",
                "ransack",
                "loot",
                "massacre",
                "destroy",
                "threaten",
                "death threat",
                "anonymous bomb threat",
                "warn",
                "intimidate",
                "harass",
                "coerce",
                "recruit",
                "conscript",
                "conscription",
                "abduct",
                "kidnap",
                "seize",
                "take hostage",
                "rape",
                "sexual assault",
                "molest",
                "sexual slavery",
                "coerced sex",
                "occupy",
                "commandeer",
                "garrison",
                "use as barracks",
                "station troops",
                "fortify",
                "base",
                "store weapons",
                "stockpile",
                "blaze",
                "on fire",
                "caught fire",
                "caught on fire",
                "catch fire",
                "flames",
                "burning",
                "take positions",
                "took positions",
                "taking positions",
                "military presence",
                "armed presence",
                "deploy",
                "deployment",
                "station",
            ],
            "target_linkers": [
                "at",
                "on",
                "against",
                "in",
                "inside",
                "outside",
                "near",
                "into",
                "towards",
                "toward",
                "by",
                "from",
            ],
            "guard_phrases": [
                "bomb squad",
                "training drill",
                "mock drill",
                "exercise drill",
                "fire drill",
                "parking ban",
                "ban parking",
                "traffic ban",
                "travel ban",
                "cyber attack",
                "phishing attack",
                "ransomware attack",
                "football attack",
                "attacking play",
                "attack the argument",
                "verbal attack",
                "peaceful protest",
                "peaceful demonstration",
                "student protest",
                "student demonstration",
                "sit-in",
                "rally",
                "march",
                "vigil",
            ],
            "protest_hints": [
                "protest",
                "demonstration",
                "sit-in",
                "rally",
                "march",
                "vigil",
                "peaceful",
            ],
            "proximity_k_default": 5,
            "proximity_k_wide": 10,
            "doc_near_k": 12,
            "explosion_lemmas": [
                "explode",
                "detonate",
                "blast",
                "explosion",
                "bomb",
                "ied",
                "device",
            ],
            "incidental_terms": [
                "damage",
                "hit",
                "strike",
                "blast",
                "explosion",
                "shrapnel",
                "debris",
                "crossfire",
                "explode",
                "detonate",
            ],
        },
        # --- Augmentation settings ---
        "augmentation": {
            "model": "gemma3:27b",
            "strategies": {
                "synonym": {
                    "enabled": False,
                    "n_variants": 1,
                },
                "paraphrase": {
                    "enabled": False,
                    "n_variants": 1,
                },
                "backtranslation_fr_zh": {
                    "enabled": False,
                    "source_language": "en",
                    "n_variants": 1,
                },
                "counterfactual": {
                    "enabled": False,
                    "n_variants": 1,
                    "num_flips": 2,
                },
            },
        },
    }
    return hyperparameters


# {0: 'Adult',
#  1: 'Art & Design',
#  10: 'Food & Dining',
#  11: 'Games',
#  12: 'Health',
#  13: 'History',
#  14: 'Home & Hobbies',
#  15: 'Industrial',
#  16: 'Literature',
#  17: 'Politics',
#  18: 'Religion',
#  19: 'Science & Tech.',
#  2: 'Software Dev.',
#  20: 'Software',
#  21: 'Sports & Fitness',
#  22: 'Transportation',
#  23: 'Travel',
#  3: 'Crime & Law',
#  4: 'Education & Jobs',
#  5: 'Hardware',
#  6: 'Entertainment',
#  7: 'Social Life',
#  8: 'Fashion & Beauty',
#  9: 'Finance & Business'}
