def get_hp_config():
    """
    Contains the hyperparameter configurations for model training.
    This configuration is "operational" so modifying these settings will impact the model's behavior during the training.

    Returns:
    - hyperparameters (dict): A dictionary containing hyperparameters for training the model.
    """
    
    hyperparameters = {
        "lr": 0.00010115394823997542,
        "alpha": 0.18579734374597295,
        "steps": [*range(1, 36 + 1, 1)],
        "n_jobs": -1,
        "dropout": 0.25,
        "n_epochs": 200,
        "batch_size": 64,
        "likelihood": None,
        "mc_dropout": True,
        "force_reset": True,
        "hidden_size": 256,
        "learn_alpha": False,
        "num_samples": 1,
        "add_encoders": {
            "position": {"past": ["relative"], "future": ["relative"]},
        },
        "random_state": 67,
        "weight_decay": 0.000001,
        "loss_function": "NegativeBinomialLoss",
        "optimizer_cls": "Adam",
        "target_scaler": None,
        "feature_scaler": None,
        "use_layer_norm": True,
        "zero_threshold": 0.5,
        "lr_scheduler_T_0": 25,
        "lr_scheduler_cls": "CosineAnnealingWarmRestarts",
        "optimizer_kwargs": {
            "lr": 0.00010115394823997542,
            "weight_decay": 0.000001,
        },
        "gradient_clip_val": 1.5,
        "inverse_transform": False,
        "decoder_output_dim": 128,
        "feature_scaler_map": {
            "MinMaxScaler": [
                "month",
                "lr_wdi_sl_tlf_totl_fe_zs",
                "lr_wdi_se_enr_prim_fm_zs",
                "lr_wdi_sp_urb_totl_in_zs",
                "lr_vdem_v2x_horacc",
                "lr_vdem_v2x_veracc",
                "lr_vdem_v2x_diagacc",
                "lr_vdem_v2xnp_client",
                "lr_vdem_v2xnp_regcorr",
                "lr_vdem_v2xpe_exlpol",
                "lr_vdem_v2xpe_exlgeo",
                "lr_vdem_v2xpe_exlgender",
                "lr_vdem_v2xpe_exlsocgr",
                "lr_vdem_v2x_divparctrl",
                "lr_vdem_v2x_ex_party",
                "lr_vdem_v2x_ex_military",
                "lr_vdem_v2x_genpp",
                "lr_vdem_v2xeg_eqdr",
                "lr_vdem_v2xcl_prpty",
                "lr_vdem_v2xeg_eqprotec",
                "lr_vdem_v2xcl_dmove",
                "lr_vdem_v2x_clphy",
                "lr_topic_ste_theta0_stock_t1",
                "lr_topic_ste_theta0_stock_t2",
                "lr_topic_ste_theta0_stock_t13",
                "lr_topic_ste_theta1_stock_t1",
                "lr_topic_ste_theta1_stock_t2",
                "lr_topic_ste_theta1_stock_t13",
                "lr_topic_ste_theta2_stock_t1",
                "lr_topic_ste_theta2_stock_t2",
                "lr_topic_ste_theta2_stock_t13",
                "lr_topic_ste_theta3_stock_t1",
                "lr_topic_ste_theta3_stock_t2",
                "lr_topic_ste_theta3_stock_t13",
                "lr_topic_ste_theta4_stock_t1",
                "lr_topic_ste_theta4_stock_t2",
                "lr_topic_ste_theta4_stock_t13",
                "lr_topic_ste_theta5_stock_t1",
                "lr_topic_ste_theta5_stock_t2",
                "lr_topic_ste_theta5_stock_t13",
                "lr_topic_ste_theta6_stock_t1",
                "lr_topic_ste_theta6_stock_t2",
                "lr_topic_ste_theta6_stock_t13",
                "lr_topic_ste_theta7_stock_t1",
                "lr_topic_ste_theta7_stock_t2",
                "lr_topic_ste_theta7_stock_t13",
                "lr_topic_ste_theta8_stock_t1",
                "lr_topic_ste_theta8_stock_t2",
                "lr_topic_ste_theta8_stock_t13",
                "lr_topic_ste_theta9_stock_t1",
                "lr_topic_ste_theta9_stock_t2",
                "lr_topic_ste_theta9_stock_t13",
                "lr_topic_ste_theta10_stock_t1",
                "lr_topic_ste_theta10_stock_t2",
                "lr_topic_ste_theta10_stock_t13",
                "lr_topic_ste_theta11_stock_t1",
                "lr_topic_ste_theta11_stock_t2",
                "lr_topic_ste_theta11_stock_t13",
                "lr_topic_ste_theta12_stock_t1",
                "lr_topic_ste_theta12_stock_t2",
                "lr_topic_ste_theta12_stock_t13",
                "lr_topic_ste_theta13_stock_t1",
                "lr_topic_ste_theta13_stock_t2",
                "lr_topic_ste_theta13_stock_t13",
                "lr_topic_ste_theta14_stock_t1",
                "lr_topic_ste_theta14_stock_t2",
                "lr_topic_ste_theta14_stock_t13",
                "lr_topic_ste_theta0_stock_t1_splag",
                "lr_topic_ste_theta1_stock_t1_splag",
                "lr_topic_ste_theta2_stock_t1_splag",
                "lr_topic_ste_theta3_stock_t1_splag",
                "lr_topic_ste_theta4_stock_t1_splag",
                "lr_topic_ste_theta5_stock_t1_splag",
                "lr_topic_ste_theta6_stock_t1_splag",
                "lr_topic_ste_theta7_stock_t1_splag",
                "lr_topic_ste_theta8_stock_t1_splag",
                "lr_topic_ste_theta9_stock_t1_splag",
                "lr_topic_ste_theta10_stock_t1_splag",
                "lr_topic_ste_theta11_stock_t1_splag",
                "lr_topic_ste_theta12_stock_t1_splag",
                "lr_topic_ste_theta13_stock_t1_splag",
                "lr_topic_ste_theta14_stock_t1_splag",
            ],
            "AsinhTransform": [
                "lr_wdi_sm_pop_refg_or",
                "lr_wdi_ny_gdp_mktp_kd",
                "lr_wdi_nv_agr_totl_kn",
                "lr_splag_1_ged_sb",
                "lr_splag_1_ged_ns",
                "lr_splag_1_ged_os",
                "lr_topic_tokens_t1",
                "lr_topic_tokens_t2",
                "lr_topic_tokens_t13",
                "lr_topic_tokens_t1_splag",
            ],
            "StandardScaler": [
                "lr_ged_sb_delta",
                "lr_ged_ns_delta",
                "lr_ged_os_delta",
                "lr_wdi_sm_pop_netm",
                "lr_wdi_dt_oda_odat_pc_zs",
                "lr_wdi_sp_pop_grow",
                "lr_wdi_ms_mil_xpnd_gd_zs",
                "lr_wdi_sp_dyn_imrt_fe_in",
                "lr_wdi_sh_sta_stnt_zs",
                "lr_wdi_sh_sta_maln_zs",
            ],
        },
        "input_chunk_length": 48,
        "num_decoder_layers": 2,
        "num_encoder_layers": 2,
        "output_chunk_shift": 0,
        "temporal_precision": "month",
        "use_datetime_index": False,
        "lr_scheduler_T_mult": 1,
        "lr_scheduler_kwargs": {
            "T_0": 25,
            "T_mult": 1,
            "eta_min": 0.000001,
        },
        "output_chunk_length": 36,
        "temporal_width_past": 24,
        "lr_scheduler_eta_min": 0.000001,
        "false_negative_weight": 1,
        "false_positive_weight": 3.9982222288208185,
        "temporal_width_future": 64,
        "use_static_covariates": True,
        "early_stopping_patience": 30,
        "temporal_decoder_hidden": 256,
        "early_stopping_min_delta": 0.0001,
        "temporal_hidden_size_past": 256,
        "temporal_hidden_size_future": 128,
        "use_reversible_instance_norm": False,
    }

    return hyperparameters