def get_hp_config():
    """
    Contains the hyperparameter configurations for model training.
    This configuration is "operational" so modifying these settings will impact the model's behavior during the training.

    Returns:
    - hyperparameters (dict): A dictionary containing hyperparameters for training the model, which determine the model's behavior during the training phase.
    """

    hyperparameters = {
        "steps": [*range(1, 36 + 1, 1)],
        "add_relative_index": True,
        "batch_size": 32,
        "delta": 0.5171875867286464,
        "dropout": 0.1,
        "early_stopping_min_delta": 0.001,
        "early_stopping_patience": 15,
        "false_negative_weight": 3.6271104301102377,
        "false_positive_weight": 1.6031067082480173,
        "feature_scaler": None,
        "feature_scaler_map": {
            "AsinhTransform->MinMaxScaler": [
                "lr_ged_sb",
                "lr_ged_ns",
                "lr_ged_os",
                "lr_acled_sb",
                "lr_acled_sb_count",
                "lr_acled_os",
                "lr_ged_sb_tsum_24",
                "lr_splag_1_ged_sb",
                "lr_splag_1_ged_os",
                "lr_splag_1_ged_ns",
                "lr_wdi_ny_gdp_mktp_kd",
                "lr_wdi_nv_agr_totl_kn",
                "lr_wdi_sm_pop_netm",
                "lr_wdi_sm_pop_refg_or",
            ],
            "MinMaxScaler": [
                "lr_wdi_sl_tlf_totl_fe_zs",
                "lr_wdi_se_enr_prim_fm_zs",
                "lr_wdi_sp_urb_totl_in_zs",
                "lr_wdi_sh_sta_maln_zs",
                "lr_wdi_sh_sta_stnt_zs",
                "lr_wdi_dt_oda_odat_pc_zs",
                "lr_wdi_ms_mil_xpnd_gd_zs",
                "lr_vdem_v2x_horacc",
                "lr_vdem_v2xnp_client",
                "lr_vdem_v2x_veracc",
                "lr_vdem_v2x_divparctrl",
                "lr_vdem_v2xpe_exlpol",
                "lr_vdem_v2x_diagacc",
                "lr_vdem_v2xpe_exlgeo",
                "lr_vdem_v2xpe_exlgender",
                "lr_vdem_v2xpe_exlsocgr",
                "lr_vdem_v2x_ex_party",
                "lr_vdem_v2x_genpp",
                "lr_vdem_v2xeg_eqdr",
                "lr_vdem_v2xcl_prpty",
                "lr_vdem_v2xeg_eqprotec",
                "lr_vdem_v2x_ex_military",
                "lr_vdem_v2xcl_dmove",
                "lr_vdem_v2x_clphy",
                "lr_vdem_v2x_hosabort",
                "lr_vdem_v2xnp_regcorr",
                "lr_topic_ste_theta0",
                "lr_topic_ste_theta1",
                "lr_topic_ste_theta2",
                "lr_topic_ste_theta3",
                "lr_topic_ste_theta4",
                "lr_topic_ste_theta5",
                "lr_topic_ste_theta6",
                "lr_topic_ste_theta7",
                "lr_topic_ste_theta8",
                "lr_topic_ste_theta9",
                "lr_topic_ste_theta10",
                "lr_topic_ste_theta11",
                "lr_topic_ste_theta12",
                "lr_topic_ste_theta13",
                "lr_topic_ste_theta14",
                "lr_topic_ste_theta0_stock_t1_splag",
                "lr_topic_ste_theta1_stock_t1_splag",
                "lr_topic_ste_theta2_stock_t1_splag",
                "lr_topic_ste_theta3_stock_t1_splag",
                "lr_topic_ste_theta4_stock_t1_splag",
                "lr_topic_ste_theta5_stock_t1_splag",
                "lr_topic_ste_theta6_stock_t1_splag",
                "lr_topic_ste_theta7_stock_t1_splag",
                "lr_topic_ste_theta8_stock_t1_splag",
                "lr_topic_ste_theta9_stock_t1_splag",
                "lr_topic_ste_theta10_stock_t1_splag",
                "lr_topic_ste_theta11_stock_t1_splag",
                "lr_topic_ste_theta12_stock_t1_splag",
                "lr_topic_ste_theta13_stock_t1_splag",
                "lr_topic_ste_theta14_stock_t1_splag",
            ],
            "RobustScaler->MinMaxScaler": [
                "lr_topic_tokens_t1",
                "lr_topic_tokens_t1_splag",
            ],
            "SqrtTransform->MinMaxScaler": [
                "lr_wdi_sp_dyn_imrt_fe_in",
            ],
            "StandardScaler->MinMaxScaler": [
                "lr_wdi_sp_pop_grow",
            ],
        },
        "feed_forward": "GatedResidualNetwork",
        "force_reset": True,
        "full_attention": True,
        "gradient_clip_val": 0.7639376582774409,
        "hidden_continuous_size": 8,
        "hidden_size": 128,
        "input_chunk_length": 48,
        "likelihood": None,
        "loss_function": "WeightedPenaltyHuberLoss",
        "lr": 3.0463850116629113e-05,
        "lr_scheduler_cls": "ReduceLROnPlateau",
        "lr_scheduler_factor": 0.3093250299228261,
        "lr_scheduler_kwargs/factor": 0.3093250299228261,
        "lr_scheduler_kwargs/min_lr": 1e-07,
        "lr_scheduler_kwargs/mode": "min",
        "lr_scheduler_kwargs/monitor": "train_loss",
        "lr_scheduler_kwargs/patience": 5,
        "lr_scheduler_min_lr": 1e-07,
        "lr_scheduler_patience": 5,
        "lstm_layers": 1,
        "n_epochs": 300,
        "non_zero_weight": 3.050983867502147,
        "norm_type": "LayerNorm",
        "num_attention_heads": 4,
        "num_static_components": 1,
        "optimizer_cls": "Adam",
        "optimizer_kwargs/lr": 3.0463850116629113e-05,
        "optimizer_kwargs/weight_decay": 0.00019147515943681648,
        "output_chunk_length": 36,
        "output_chunk_shift": 0,
        "target_scaler": "RobustScaler->MinMaxScaler",
        "use_reversible_instance_norm": True,
        "use_static_covariates": True,
        "weight_decay": 0.00019147515943681648,
        "zero_threshold": 0.012159729018514571,
    }

    return hyperparameters
