def get_hp_config():
    # SMOKE (transient): gated_nb D×K=4×4 40L seed=43
    return {   'time_col': 'month_id',
    'id_col': 'priogrid_gid',
    'spatial_cols': ['row', 'col'],
    'identity_cols': ['month_id', 'priogrid_gid', 'c_id', 'row', 'col'],
    'index_names': ['month_id', 'priogrid_gid'],
    'features': ['lr_sb_best', 'lr_ns_best', 'lr_os_best'],
    'input_channels': 3,
    'row_offset': 87,
    'col_offset': 310,
    'height': 180,
    'width': 180,
    'model': 'HydraBNUNet06_LSTM4',
    'total_hidden_channels': 32,
    'dropout_rate': 0.125,
    'window_dim': 32,
    'output_channels': 1,
    'weight_init': 'xavier_norm',
    'h_init': 'abs_rand_exp-100',
    'windows_per_lesson': 3,
    'learning_rate': 0.001,
    'weight_decay': 0.1,
    'scheduler': 'WarmupDecay',
    'warmup_steps': 100,
    'clip_grad_norm': True,
    'torch_seed': 43,
    'np_seed': 43,
    'classification_targets': ['by_sb_best', 'by_ns_best', 'by_os_best'],
    'regression_targets': ['lr_sb_best', 'lr_ns_best', 'lr_os_best'],
    'transformations': {   'log1p': ['lr_sb_best', 'lr_ns_best', 'lr_os_best'],
                           'asinh': [],
                           'identity': []},
    'derivations': {   'binary': [   {'from': 'lr_sb_best', 'to': 'by_sb_best', 'threshold': 0},
                                     {'from': 'lr_ns_best', 'to': 'by_ns_best', 'threshold': 0},
                                     {'from': 'lr_os_best', 'to': 'by_os_best', 'threshold': 0}]},
    'steps': [   1,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36],
    'time_steps': 36,
    'loss_reg': 'mse',
    'loss_class': 'weighted_bce',
    'loss_class_alpha': 0.75,
    'loss_class_gamma': 1.5,
    'onset_bias_init': -7.0,
    'ss_schedule': 'linear',
    'ss_warmup_lessons': 10,
    'ss_epsilon_max': 0.5,
    'total_lessons': 160,
    'max_ratio': 0.95,
    'min_ratio': 0.05,
    'slope_ratio': 0.75,
    'roof_ratio': 0.7,
    'min_events': 5,
    'sampling_strategy': 'threshold',
    'n_posterior_samples': 4,
    'evaluation_mode': 'stochastic',
    'aggregate_method': 'arithmetic_mean',
    'skip_predictions_delivery': True,
    'output_distribution': 'nb',
    'forecast_composition': 'soft_gate',
    'n_head_samples': 4,
    'reg_activation': 'softplus',
    'body_supervision': 'all',
    'rollout_feedback': 'sample',
    'bn_recalibrate': True,
    'loss_class_pos_weight': 2.0}
