def get_hp_config():
    """TiDE training configuration for GDP disaggregation with conflict features."""
    return {
        "steps": [*range(1, 36 + 1)],
        "time_steps": 36,
        "n_jobs": -1,
        "input_chunk_length": 36,
        "output_chunk_length": 36,
        "output_chunk_shift": 0,
        "hidden_size": 256,
        "decoder_output_dim": 64,
        "temporal_decoder_hidden": 96,
        "temporal_width_past": 32,
        "temporal_width_future": 3,
        "temporal_hidden_size_past": 96,
        "temporal_hidden_size_future": 16,
        "num_encoder_layers": 2,
        "num_decoder_layers": 2,
        "use_layer_norm": True,
        "use_reversible_instance_norm": False,
        "dropout": 0.3,
        "use_static_covariates": True,
        "n_epochs": 300,
        "batch_size": 128,
        "random_state": 67,
        "force_reset": True,
        "optimizer_cls": "AdamW",
        "lr": 2e-4,
        "weight_decay": 5e-5,
        "optimizer_kwargs": {"lr": 2e-4, "weight_decay": 5e-5},
        "lr_scheduler_cls": "ReduceLROnPlateau",
        "lr_scheduler_factor": 0.5,
        "lr_scheduler_patience": 5,
        "lr_scheduler_min_lr": 3e-6,
        "lr_scheduler_kwargs": {
            "mode": "min", "factor": 0.5, "patience": 5, "min_lr": 3e-6,
            "cooldown": 0, "threshold": 0.002, "threshold_mode": "rel",
        },
        "early_stopping_monitor": "val_metrics/MSLE",
        "lr_scheduler_monitor": "val_metrics/MSLE",
        "gradient_clip_val": 25.0,
        "early_stopping_patience": 12,
        "early_stopping_min_delta": 0.002,
        "loss_function": "SpotlightLossLogcosh",
        "non_zero_threshold": 0.88,
        "likelihood": None,
        "num_samples": 1,
        "mc_dropout": False,
        "target_scaler": "AsinhTransform",
        "feature_scaler": None,
        "force_target_only": True,
        "feature_scaler_map": {
            "AsinhTransform": ["lr_ged_sb", "lr_ged_os", "lr_ged_ns", "lr_pop_totl"]
        },
        "use_cyclic_encoders": False,
        "temporal_disaggregation": {
            target: {"method": "denton-cholette", "conversion": "average"}
            for target in (
                "lr_gdp_pcap", "lr_ttns_zs", "lr_imrt_in", "lr_le00_in",
                "lr_chex_gd_zs", "lr_chex_gd_pcap", "lr_stnt_me_zs",
                "lr_defc_zs", "lr_prm_enrr", "lr_v2x_libdem",
            )
        },
    }
