name: Update Model Catalogs
on:
  push:
    branches:
      - create_catalogs_01 # for testing on this branch
      - main
      - development
    paths:
      - models/*/configs/config_*.py
      - ensembles/*/configs/config_*.py
  workflow_dispatch: # for triggering manually

jobs:
  check-new-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: views-platform/views-models
          token: ${{ secrets.VIEWS_MODELS_ACCESS_TOKEN }}
          #fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install views_pipeline_core


      - name: Generate catalog if models directory has changed
        run: |
          python create_catalogs.py  
          python update_readme.py
          if [ $? -ne 0 ]; then
            echo "Generating catalogs failed."
            exit 1
          fi
          echo "Model catalog is updated. Model READMEs are updated."           
          git status

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add README.md models/ ensembles/
          git commit -m "Automated changes by GitHub Actions" || echo "Nothing to commit"
          git push https://${{ secrets.VIEWS_MODELS_ACCESS_TOKEN }}@github.com/views-platform/views-models.git
      
